imageName: "chrisgallivan/automate-all-the-things-docker"
bucketName: ""
backendFile: "terraformConfig.tf"
backendPath: "global/s3/terraform.tfstate"
registryCredential: "docker_hub"
slackToken: ""
slackChannel: "general-old"
successAction: "curl -X POST https://maker.ifttt.com/trigger/jenkins_success/with/key/geqAu4WK7xgLcr4md038_CrKCsXrRjZbJ9MsQBwPLg9"
failureAction: "curl -X POST https://maker.ifttt.com/trigger/jenkins_failure/with/key/geqAu4WK7xgLcr4md038_CrKCsXrRjZbJ9MsQBwPLg9"
